import type { Metadata } from "next";
import { Inter, Lora } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import LuxuryHeader from "@/components/LuxuryHeader";
import Footer from "@/components/Footer";
import LayoutWrapper from "@/components/LayoutWrapper";
import { AuthProvider } from "@/components/AuthProvider";
import { getSettings, getBranding } from "@/lib/settings";
import { getMainNavigation, getFooterNavigation, groupFooterLinks } from "@/lib/navigation";
import { getHomepageData } from "@/lib/homepage";

// Inter - Clean, modern sans-serif for body text
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  display: "swap",
});

// Lora - Elegant serif for headings
const lora = Lora({
  variable: "--font-lora",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch settings, navigation, and homepage data
  const [settings, branding, mainNav, footerNav, homepage] = await Promise.all([
    getSettings(),
    getBranding(),
    getMainNavigation(),
    getFooterNavigation(),
    getHomepageData(),
  ]);

  const footerColumns = groupFooterLinks(footerNav);
  const isLuxuryTemplate = homepage?.template === 'luxury';

  return (
    <html lang="en">
      <body className={`${inter.variable} ${lora.variable} antialiased`}>
        <AuthProvider>
        <LayoutWrapper
          header={
            isLuxuryTemplate ? (
              <LuxuryHeader
                logo={branding?.logo}
                logoAlt={branding?.logoAlt || settings?.title}
                siteTitle={settings?.title}
                navItems={mainNav}
                phoneNumber={settings?.contactInfo?.phone}
                email={settings?.contactInfo?.email}
              />
            ) : (
              <Header
                logo={branding?.logo}
                logoAlt={branding?.logoAlt || settings?.title}
                siteTitle={settings?.title}
                navItems={mainNav}
              />
            )
          }
          footer={
            <Footer
              logo={branding?.logo}
              logoAlt={branding?.logoAlt || settings?.title}
              siteTitle={settings?.title}
              description={settings?.description}
              columns={footerColumns}
              socialMedia={settings?.socialMedia}
              contactInfo={settings?.contactInfo}
              footer={settings?.footer}
            />
          }
        >
          {children}
        </LayoutWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
